### ISSUE TITLE
sample code is not clear

### ISSUE THREAD

**Issue by vastril4o** [nostra13/Android-Universal-Image-Loader#1000]
// Load image, decode it to Bitmap and display Bitmap in ImageView (or any other view 
//  which implements ImageAware interface)
imageLoader.displayImage(imageUri, imageView);

So where imageLoader came from???

ImageLoader imageLoader = new ImageLoader();
this not work... ???

Please recreate sample code for better lib performance.

**Comment by jatwigg** [comment]
in README it states
* Useful Info - Read it before asking a question

If you follow that link you find
```
// Then later, when you want to display image
ImageLoader.getInstance().displayImage(imageUrl, imageView); // Default options will be used
```

In README it also states
* User Support - Read it before creating new issue

if you follow that link you find
1. Look into Useful Info

**Comment by nostra13** [comment]
@jatwigg :+1: :)

**Comment by vastril4o** [comment]
OK, you are right, BUT if a want to take quick decision to use your api or another one, i don`t want to spend time on reading README files at the beginning.
I just want to find a easiest way to load images, and I make my decision fast :)

Its your api, its your choice. I'm just trying to help you, because adding 1 row to your SIMPLE code (that's how you name it) will save me time, and save other users time too :)
this the currect row: "ImageLoader.getInstance().displayImage(imageUrl, imageView);"

This is SIMPLE code
ImageLoader.getInstance().displayImage(imageUrl, imageView);

This is confusing 1 LINE code ever read from your api, you name it SIMPLE.
imageLoader.displayImage(imageUri, imageView);

Happy coding :)

**Comment by nostra13** [comment]
> i don`t want to spend time on reading README files at the beginning

That's not right :) Readme is the 1st, sample project is the 2nd thing to look into.
Anyway - 070e4180d080dbca5f45ac54cdaef101d314bcf0
