### ISSUE TITLE
UIL doesn't support scheme(protocol) by default [ http://46.101.36.237/apps/magicmind/v1/upload_package/c.jpg].

### ISSUE THREAD

**Issue by motameni** [nostra13/Android-Universal-Image-Loader#1015]
Hi guys.
I get this error:

UIL doesn't support scheme(protocol) by default [ http://46.101.36.237/apps/magicmind/v1/upload_package/c.jpg].

I before loaded images from my domain successfully and now just change my domain to ip address.
What is wrong!?
TNX

**Comment by nostra13** [comment]
Is there `\n` in the beginning of URL?

**Comment by motameni** [comment]
There was extra space. problem solved. TNX
