### ISSUE TITLE
Restrict image loading while list scrolling

### ISSUE THREAD

**Issue by gbrbks** [nostra13/Android-Universal-Image-Loader#106]
Hello!

The library is great but I have a question. Is it possible to restrict the image loading in listview just for the state of scroll idle state. So prevent loading when scrolling to boost up performance.

Thank in advance!

Best Regards.

**Comment by SanjayKMath** [comment]
Hi,
     On scroll of the listView the images are that are wrong one's at all listview  row position, but later it will load with the correct one's. How i can fix this, I have used ViewHolder static class as given in the sample.

**Comment by SherlockOy** [comment]
@SanjayKMath late, but just in case, you can try to set a default image after getTag() in the getView() function
