### ISSUE TITLE
Images once loaded, reloads while scrolling in recylerview

### ISSUE THREAD

**Issue by vipulasri** [nostra13/Android-Universal-Image-Loader#1067]
Images once loaded, reloads while scrolling in recylerview. Is there any way to make it work like facebook android app feed.that is Images once loaded doesn't loads again even scrolling back to same position

**Comment by devkhan** [comment]
I am having the same issue. Can anyone fix this?

**Comment by vipulasri** [comment]
I figured out the way to do so, By inflating the imageview with images that are already in cache. Have a look at the sample code.

            File file = imageLoader.getDiskCache().get(image_url);
            if (file==null) {
                //Log.e("network load", "");
            }
            else{
                mImageView.setImageURI(Uri.parse(file.getAbsolutePath()));
                //Log.e("cache load", "");
            }
