### ISSUE TITLE
i use your sample -> listview,   picture distortion 

### ISSUE THREAD

**Issue by buffol** [nostra13/Android-Universal-Image-Loader#1156]
ver 1.9.3，1.9.5 test, picture distortion 
options = new DisplayImageOptions.Builder()
					.showImageOnLoading(R.drawable.ic_stub)
					.showImageForEmptyUri(R.drawable.ic_empty)
					.showImageOnFail(R.drawable.ic_error)
					.cacheInMemory(false)
					.cacheOnDisk(false)
					.considerExifParams(true)
					.displayer(new RoundedBitmapDisplayer(360))
					.build();

but ,ver 1.8.6 picture  is normal

so ,i want to know，how set this DisplayImageOptions，Let picture  become normal.??

**Comment by buffol** [comment]
i find solution。。。
www.cnblogs.com/wan1976/p/5008751.html
this guy overwrite RoundedBitmapDisplayer class,

**Comment by MIkeeJY** [comment]
bump
