### ISSUE TITLE
Save image into a specifyc folder

### ISSUE THREAD

**Issue by rflores00** [nostra13/Android-Universal-Image-Loader#1162]
Is any change to save the image downloaded from an URL to another folder like myappImageFolder?

**Comment by gikarasojo** [comment]
// Load image, decode it to Bitmap and display Bitmap in ImageView (or any other view 
//  which implements ImageAware interface)


    imageLoader.displayImage(imageUri, imageView, options, new ImageLoadingListener() {
    @Override
    public void onLoadingStarted(String imageUri, View view) {
        ...
    }
    @Override
    public void onLoadingFailed(String imageUri, View view, FailReason failReason) {
        ...
    }
    @Override
    public void onLoadingComplete(String imageUri, View view, Bitmap loadedImage) {
        ...
    }
    @Override
    public void onLoadingCancelled(String imageUri, View view) {
        ...
    }
    }, new ImageLoadingProgressListener() {
    @Override
    public void onProgressUpdate(String imageUri, View view, int current, int total) {
        ...
     }
    });

**you can get the bitmap in method onLoadingComplete and save it to a file**

**Comment by rflores00** [comment]
Oh Really?, thanks so much!
