### ISSUE TITLE
Download only over WiFi but always use cache

### ISSUE THREAD

**Issue by nicomott** [nostra13/Android-Universal-Image-Loader#117]
Because I have large pictures in a part of my app, I want to give the user an option to download these pictures only if he is using WiFi.

UIL doesn't seem to have an option for that, and it may be deliberate.

Anyway, I've implemented the connection check in my app, but I'd want at least to be able to display the picture from UIL cache if WiFi isn't available. Something like mImageLoader.displayImageFromCache(....); 
I don't know if this method isn't there by choice. For now, I manually check on the DiscCache if the file is there, if so I call the classic displayImage

Did I miss something ?

**Comment by simontom** [comment]
Hello,
please, is there any way how to let the UIM download the stuff ONLY on WiFi?
OR
How to let it displayImage ONLY from the Cache source not the URL one?

By the way, pretty cool Lib! ;-P

**Comment by simontom** [comment]
Oh, sorry, I forgot to think a little more.
The way how to do that is to extend UIL's default BaseImageDownloader.
