### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by gedeju** [nostra13/Android-Universal-Image-Loader#1182]
how can i fix this error. pls help me.  thank you.

----------------------------------------------------------------------------------
02-15 20:27:26.403 20485-20485/? E/dalvikvm: Could not find class 'com.nostra13.universalimageloader.cache.memory.impl.FuzzyKeyMemoryCache', referenced from method com.nostra13.universalimageloader.core.ImageLoaderConfiguration$Builder.initEmptyFieldsWithDefaultValues
02-15 20:27:26.413 20485-20485/? E/AndroidRuntime: FATAL EXCEPTION: main
02-15 20:27:26.413 20485-20485/? E/AndroidRuntime: java.lang.NoClassDefFoundError: com.nostra13.universalimageloader.core.assist.QueueProcessingType
02-15 20:27:26.413 20485-20485/? E/AndroidRuntime:     at com.nostra13.universalimageloader.core.ImageLoaderConfiguration$Builder.<clinit>(ImageLoaderConfiguration
----------------------------------------------------------------------------------

**Comment by VanditPatel** [comment]
Hi,

    I am facing this issue in library version 1.9.2. Any updates on this issue?
