### ISSUE TITLE
Animated stub image

### ISSUE THREAD

**Issue by frankred** [nostra13/Android-Universal-Image-Loader#122]
Hi , first of all i wanted to say that this project is very awesome :)

Now my question, is it possible to have an animated "loader image" like a "gif"  as a stub image.?
Like in Screenshot https://github.com/nostra13/Android-Universal-Image-Loader/raw/master/UniversalImageLoader.png in the third picture.

Greets Frank Roth

**Comment by vlivanov** [comment]
What about casting view to ImageView and calling getDrawable() ?
