### ISSUE TITLE
Load and cache images

### ISSUE THREAD

**Issue by SahilMunjal** [nostra13/Android-Universal-Image-Loader#1225]
How to load and cache images without being displayed on any ImageView and to display it in future from cache whenever required.

**Comment by zhaoweiguo** [comment]
`mImageLoader.displayImage(imgUrl, new ImageView(mActivity), options);`
May be ok.

**Comment by SahilMunjal** [comment]
Thank You but I have used this and it worked fine.

ImageLoader.getInstance().loadImageSync(link, options);
