### ISSUE TITLE
Does Android-Universal-Image-Loader support Asset folder?

### ISSUE THREAD

**Issue by mrleolink** [nostra13/Android-Universal-Image-Loader#123]
Hi nostra13,

I was going to use this lib in my project, but after some searches, I couldn't figure out how to use this lib to load images from assets folder, even when I used "file:///android_asset/... , it didn't work.

``` java
        mImageLoader.displayImage("file:///android_asset/" + path, 
                iv, Const.displayImageOptions, 
                new SimpleImageLoadingListener()
        {
            @Override
            public void onLoadingComplete(Bitmap loadedImage) {
                Animation anim = AnimationUtils
                        .loadAnimation(mContext, R.anim.fade_in);
                iv.setAnimation(anim);
                anim.start();
            }
        }); 
```

If it's possible, could you provide me some code? or even if I have to customized some code myself, please let me know how to do it.

Thanks in advance and sorry for my bad English :)

**Comment by YuvPrime** [comment]
@nostra13 Where is `ExtendedImageDownloader`? I couldn't find in your project. Can you pl give me the link?

**Comment by nostra13** [comment]
`assets://...` scheme is supported out of box now

**Comment by YuvPrime** [comment]
Thanks, it's working.

**Comment by zdd** [comment]
Can I use subfolders in assets folder?
like this assets://images/test.png
