### ISSUE TITLE
Same URL with different images

### ISSUE THREAD

**Issue by z85510** [nostra13/Android-Universal-Image-Loader#1319]
I have one URL for Image and image changes sometimes, How can I use cache based on update-time ?
I have Update-time when image was changed and I try to load ***.jpg#2018-9-8 and when it changes I try to load ***.jpg#2018-9-9, but Library use cache and display first image.

What's the solution ?

**Comment by li9ht** [comment]
i did something like this. ***.jpg?time=123123232323
im using timetime.. picture is updated every 5 minute.. and its working.. mine is in the a listview..
