### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by giaur500** [nostra13/Android-Universal-Image-Loader#1337]
It looks like abandoned now. Is there any fork that is still maintained?

**Comment by giaur500** [comment]
Nope

**Comment by MIkeeJY** [comment]
@giaur500, did you find it yet?

**Comment by DanAtApex** [comment]
I created a PR to fix the problem but obviously without the repo being maintained, it may never be merged:

https://github.com/nostra13/Android-Universal-Image-Loader/pull/1348

Here is my fork:

https://github.com/DanAtApex/Android-Universal-Image-Loader

**Comment by giaur500** [comment]
I'd suggest to use Glide. Universal Image Loader is dead definitely, Picasso seems to be dead too, afaik Glide is the only option

**Comment by nostra13** [comment]
I think UIL and Picasso just reached the peak of excellence so they don't need to be maintained :)

**Comment by MIkeeJY** [comment]
@nostra13 Tell me about it,bump!
