### ISSUE TITLE
Loading bitmap with too large height 

### ISSUE THREAD

**Issue by kapilrajputmps** [nostra13/Android-Universal-Image-Loader#1338]
I am facing a issue while loading bitmap in imageview of too large height of images but size of images is less than 2MB. Universal Image loader destroying the quality of image and text on it is not readable and if not scaling the image then it is not showing in ImageView. I have posted the same problem in detail on stackoverflow. please check and suggest the better solution.
https://stackoverflow.com/questions/55510041/loading-bitmap-with-too-large-height-in-android-imageview

**Comment by nostra13** [comment]
Answered on StackOverFlow.
