### ISSUE TITLE
faild in Android Pie

### ISSUE THREAD

**Issue by DineshBalayan** [nostra13/Android-Universal-Image-Loader#1339]
i am using universal imageloader i.e working fine till oreo but now it is faild to load image in Pie

it is updated 
    implementation 'com.nostra13.universalimageloader:universal-image-loader:1.9.5'
right

**Comment by nostra13** [comment]
Probably because of permissions. Will check.

**Comment by MonikaJethani** [comment]
@DineshBalayan @nostra13 Is this open? Can I work on this?

**Comment by nostra13** [comment]
@MonikaJethani Sure. BTW I have no any issues on Pie :thinking:

**Comment by Nioux** [comment]
Hi,
I also have a problem with Android P when I activate the StricMode policy to detect "non sdk api usage" and target sdk = 28.

`			StrictMode.setVmPolicy(new StrictMode.VmPolicy.Builder()
					.detectNonSdkApiUsage()
					.penaltyLog()
					.build());
`

This will become a problem in some months, as Google will kill the apps using this.

Problem seems on this line in  ImageViewAware getImageViewFieldValue :
`            Field field = ImageView.class.getDeclaredField(fieldName);
`
