### ISSUE TITLE
logo proposal

### ISSUE THREAD

**Issue by davidmind** [nostra13/Android-Universal-Image-Loader#1340]
HI, I @nostra13 I am a graphics designer, I am a graphics designer. I will like to know if you want me to create a new logo for your project.

**Comment by nostra13** [comment]
Hey, why not :)

**Comment by davidmind** [comment]
Ok, I will go and make a sketch and work on logo as soon as possible.

**Comment by nostra13** [comment]
Thanks :+1:

**Comment by davidmind** [comment]
#### @nostra13 after making different sketch I came up with this, you can make suggestions on any of the design and color. 
#### I will make other sizes based on the one you choose.
<br>

![presentation-1.png](https://cdn.steemitimages.com/DQmZT11KDPoAvnD3zmkus4zSreUBqF7uK6ANEi73BMxSVyC/presentation-1.png)

**Comment by davidmind** [comment]
@nostra13 **here is a brief break down of what inspire the logo**
![Screenshot_2019-04-14-12-12-43.jpg](https://cdn.steemitimages.com/DQmbvPxuByhubwWYnkVDaVmMa9KejMH2vaeW1eEc99AEn49/Screenshot_2019-04-14-12-12-43.jpg)

**Comment by davidmind** [comment]
@mlc @nostra13 @talklittle are you there?

**Comment by nostra13** [comment]
@davidmind  Thanks for your efforts and explanation of design moves but it seems a little boring comparing to current logo :)
![](https://raw.githubusercontent.com/nostra13/Android-Universal-Image-Loader/master/sample/src/main/res/drawable-mdpi/ic_launcher.png)

My thoughts about logo with bubbles: maybe it will be cooler to use stars (from small to larger) around center-pic and try other colors.

**Comment by davidmind** [comment]
Oops i was trying to make it simple, but I will work on the star as you suggested with other colors.

**Comment by davidmind** [comment]
@nostra13 this is what it turn out to be after making use of star on the final layout of the icon
 also I try to give it a much brighter and cool color.

![PRESENTATION-3.png](https://cdn.steemitimages.com/DQmdWuRJGiQxhFGXA2PHFM45gKjU7d5eCUgDbhUi44iRSCk/PRESENTATION-3.png)

**Comment by nostra13** [comment]
I like it more, definitely :) It reminds me something... maybe Chealse FC logo :) Nevermind.
Can you make samples on white background?
I think we can remove black crescent to simplify it)

Also I would appreciate if you try different options: squared/rounded background, with/without white circles near stars, different bg colors (solid/gradient/maybe other shades of green).

**Comment by davidmind** [comment]
![Last.png](https://cdn.steemitimages.com/DQmdWZDyvi14f5z81PwAh5wU6nQ6aRq6FvtJ1pWGauukKw3/Last.png)
@nostra13 this is what I came up with

**Comment by nostra13** [comment]
I think I have my favorite) Which one do you like?

**Comment by davidmind** [comment]
![Screenshot_2019-04-19-10-53-35.jpg](https://cdn.steemitimages.com/DQmcoN1jy3AXEwkDK1u9yYqrXURSgqN5y8e8w7nKBL12Tbx/Screenshot_2019-04-19-10-53-35.jpg)

If I am to choose I will choose number 2 or 4, which of it is your favorite?

**Comment by nostra13** [comment]
I like 6/7 with solid green bg, probably `#00673a`.
Some suggestions (maybe final) to this option:
 - bg should be a perfect circle :)
 - make stars closer to edge (maybe cut out outer circle part)
 - centered pic should be perfectly aligned in the center
 - increase resolution:
        - green bg circle - 72x72dp (288x288 px)
        - whole image with transparent bg - 108x108dp (432x432 px)

**Comment by davidmind** [comment]
![uI.png](https://cdn.steemitimages.com/DQmaZ4nKAjYrmmXJZaBvTvnywieqn88JVTugDm6iA4xRkHv/uI.png)
@nostra13 have a quick look before I make it into transparent background

**Comment by nostra13** [comment]
"make stars closer to edge" I meant like this
![Screenshot from 2019-04-19 17-50-36](https://user-images.githubusercontent.com/1223348/56429513-d8ff3d80-62cb-11e9-9fb1-7a41846d48b4.png)

**Comment by davidmind** [comment]
## I made two different option for you to choose from
## 1

![5th.png](https://cdn.steemitimages.com/DQmaCnCgswRJdA7MZG1PzsZmv7UADjLF9nRV5gx3CJXXSKM/5th.png)

![3rd.png](https://cdn.steemitimages.com/DQmcnmogs7MptPmtUNm2P8EdGJsN73ybp5zvmhrLV658E7Z/3rd.png)

***
***
## 2

![done.png](https://cdn.steemitimages.com/DQmVaomZu3r7H5SBbi9CA4EveKSMcx4HponWADoaNF3q5xH/done.png)

![done2.png](https://cdn.steemitimages.com/DQmQD8t6nMb1NGoVjXgTopSXdS2nP3MYUGgj3jbszo3PgDG/done2.png)

**Comment by nostra13** [comment]
You make stars further from bg edge, not closer.

**Comment by davidmind** [comment]
I just understand what you are saying, until you mention the background edge
![final.png](https://cdn.steemitimages.com/DQmeHCpVsSRPyQKYypxjaVGYBpzLPtsfhNB6p5MjxZkeNsZ/final.png)

![final2.png](https://cdn.steemitimages.com/DQmUEXM8QuhCK1sNRCiWoGb54g7QkxvEgTyCJ9jGxZV6oqv/final2.png)

**Comment by nostra13** [comment]
Too close :) I showed the example earlier https://github.com/nostra13/Android-Universal-Image-Loader/issues/1340#issuecomment-484920037

**Comment by davidmind** [comment]
![Uii2.png](https://cdn.steemitimages.com/DQmUyuxK5J8QFtLcdaDEMmAodo6w3MjCaYZZXkqXRqBxH8D/Uii2.png)
What about now
![Uii.png](https://cdn.steemitimages.com/DQmdYGoAhVVXrfMquWn8vn3YPhghGLac5Z6J9YU4G2mS3M4/Uii.png)

**Comment by nostra13** [comment]
I like it :+1:

Last step you can do - to make it perfect. If you wish:
 - make every star at the same distance from bg edge (now it's different)
![Screenshot from 2019-04-19 20-10-31](https://user-images.githubusercontent.com/1223348/56434913-449ed600-62df-11e9-92ea-26454573bb98.png)
 - rotate whole constellation clockwise a little bit to make beginning star and ending star aligned to center-pic
  OR
 rotate whole constellation counterclock-wise a little bit to make the biggest star in the vertical center
![Screenshot from 2019-04-19 20-14-00](https://user-images.githubusercontent.com/1223348/56435055-b414c580-62df-11e9-915b-17ebdf4c8e59.png)

**Comment by davidmind** [comment]
![perfect-dem.png](https://cdn.steemitimages.com/DQmcxMtN64s4zM8EdiGBZKZC1YMCdvrnTF9Phm8sMKASiyD/perfect-dem.png)
@nostra13 sorry I was a little bit busy this days, but I just check through your last comment I have made an ammendment. Check it out
![perfect.png](https://cdn.steemitimages.com/DQmZKyGR9qKL8MVt7ra1crFL4vGpdeJgsekFGC4gccdCkep/perfect.png)

**Comment by nostra13** [comment]
I can see noticable disproportional gaps between stars (e.g. between 2nd and 3rd stars, between 6th and 7th stars, 11th and 12th). Gaps between stars should evenly decrease from the smallest to the biggest one.

**Comment by davidmind** [comment]
Oops I must have missed that up, while trying to adjust the star. I just made an amendment though the space may look unequal, using smart guide everything is equal except you want to inspect yourself through the editable file.
![full-edit.png](https://cdn.steemitimages.com/DQmedG6p3RsvYdwKmhBjEXxNfVNfdJBsL7HAnp7NVKF9CQ8/full-edit.png)

**Comment by nostra13** [comment]
Well, now I don't need a ruler to see that constellation isn't centered in the circle :)

**Comment by davidmind** [comment]
At this point i think i give up i will have to close the issue, an element like star with a non proportional size is not easy to control. The bigger the size, the beginner the space it occupied. I think you can continue from where i stop. It seems you are more knowledgable than i am.

**Comment by nostra13** [comment]
The previous logo was almost perfect (except gaps between stars). And last logo has some unexpected changes like whole constellation was moved to the left. And I can't ignore that because it can be seen with the naked eye. You as a designer should see it as well, don't you?

If you can share editable file please do it.

**Comment by davidmind** [comment]
I will share the editable file later, the bigger the resolution. The bigger the space between the star. The more i keep editing, more problem keep surfacing that is because i tend to move the whole thing from the initial postioning.

**Comment by davidmind** [comment]
Here is a link to an editable file
https://drive.google.com/folderview?id=1zlLRj6zVWOcQgRVTtGBhpcZjC-LvqQN8
