### ISSUE TITLE
java.lang.NoSuchFieldException: No field mMaxHeight in class Landroid/widget/ImageView

### ISSUE THREAD

**Issue by ashwanibhatt902** [nostra13/Android-Universal-Image-Loader#1343]
any help resolving this?
![Screen Shot 2019-07-06 at 7 45 00 PM](https://user-images.githubusercontent.com/8371995/60762115-a9d4ae80-a026-11e9-914a-c395e49f51bb.png)

**Comment by zung** [comment]
i have got the same issues. Have you resolved it yet?

**Comment by ashwanibhatt902** [comment]
No, not yet.

**Comment by ashwanibhatt902** [comment]
But I believe there might be at least 1 fork where this is fixed. I tried finding but could not find one.

**Comment by zung** [comment]
Ok, thank you.
I'll wait for your good news.
:)

**Comment by njdwklopper** [comment]
Anything happening with this ticket?

**Comment by tangjingyuan** [comment]
See the code snippet:
https://github.com/nostra13/Android-Universal-Image-Loader/blob/1af62c41b5d10503732568f0c47628762bbd8eb9/library/src/main/java/com/nostra13/universalimageloader/core/imageaware/ImageViewAware.java#L129-L141

It's printed by line 139. If you don't want to see the log you can call
` L.writeLogs(false)`
https://github.com/nostra13/Android-Universal-Image-Loader/blob/1af62c41b5d10503732568f0c47628762bbd8eb9/library/src/main/java/com/nostra13/universalimageloader/utils/L.java#L67-L69

**Comment by androidapkr** [comment]
Same issue with Android Q only 

 java.lang.NoSuchFieldException: No field mMaxHeight in class Landroid/widget/ImageView;

**Comment by tangjingyuan** [comment]
I think you can implement your owner ImageAware and define proper width/height for small image or big one.

**Comment by njdwklopper** [comment]
I moved to using Glide. Thanks

**Comment by reckos** [comment]
Are there any new informations about this ? I am getting this error and can not move forward with my project because of this...

**Comment by DanAtApex** [comment]
I created a PR to fix the problem but obviously without the repo being maintained, it may never be merged:

https://github.com/nostra13/Android-Universal-Image-Loader/pull/1348

Here is my fork:

https://github.com/DanAtApex/Android-Universal-Image-Loader

**Comment by lioriluz** [comment]
This happens because your imageview is still not inflated when you use it. Probably because you have nested fragments (childFragmentManager).
Use this to make sure the imageView is ready for use:

```
IMAGEVIEW.getViewTreeObserver().addOnGlobalLayoutListener(new ViewTreeObserver.OnGlobalLayoutListener() {
                @Override
                public void onGlobalLayout() {
                    IMAGEVIEW.getViewTreeObserver().removeOnGlobalLayoutListener(this););
                    //Load an image to your IMAGEVIEW here
                }
            });
```
