### ISSUE TITLE
Remove image from caches

### ISSUE THREAD

**Issue by anandkumarpatel** [nostra13/Android-Universal-Image-Loader#138]
Hey i'd like to first say this was a lifesaver for an app I am working on. I was plagued with outofmemory issue until I used your library. I would like to request a feature for removing a single image from the cache. The reason for this is in my application I use a listview to display some images. Now the user can change the image by clicking on it. However in my implementation I name the images in a particular way ie. the image in position one will be labeled home_position1.jpg. now when I want to change that image to another one I rename the image with that naming convention and reload the image. however since it is the same name the cache still displays the old image. I know there is the clearCache option but then that blows away the other images when they didn't change and they will be recached. I would think a remove single item from the cache would solve this problem. something like:
in BaseDiscCache:

``` java
    public void removeItem(String imageUri) {
        String fileName = fileNameGenerator.generate(key);
     File deleteMe = new File(cacheDir, fileName);
                deleteMe..delete()
    }
```

and in BaseMemoryCache

``` java
    public void removeItem(String imageUri) {
        ImageSize targetSize = getImageSizeScaleTo(imageView);
        String memoryCacheKey = MemoryCacheUtil.generateKey(uri, targetSize);
        softMap.remove(memoryCacheKey);
    }
```

**Comment by Wolf00Bomber** [comment]
The solution proposed by you doesn't work for removing image from disc cache:

File imageFile = imageLoader.getDiscCache().get(imageUri)
if (imageFile.exists()) {
    imageFile.delete();
}

Can you please suggest me another solution.

**Comment by parthibanm104** [comment]
Hi, I'm using the below codes for clearing cache memory but it doesn't works for me:
MemoryCacheUtils.removeFromCache(
					ConstantVariables.sellDetails_stringURL,
					imageLoader.getMemoryCache());
			DiskCacheUtils.removeFromCache(
					ConstantVariables.sellDetails_stringURL,
					imageLoader.getDiskCache());

Also I've used the following code to clear the disc cache:

File imageFile = imageLoader.getDiscCache().get(imageUri)
if (imageFile.exists()) {
    imageFile.delete();
}

but doesn't works for me...
Can you please give me suggestion?

**Comment by oseamiya** [comment]
public void DeleteCachedImage(String imageUrl){
        ImageLoaderConfiguration config = new ImageLoaderConfiguration.Builder(this.context).build();
        (this.imgLoader = ImageLoader.getInstance()).init(config);
        final ImageLoader imgLoader = this.imgLoader;
        ImageLoader.getInstance().getDiskCache().get(imageUrl).delete();
}

This should help you .
