### ISSUE TITLE
Task was interrupted ERROR

### ISSUE THREAD

**Issue by dazhucc** [nostra13/Android-Universal-Image-Loader#144]
My screen is 480X800 and the image is 600X230.It's OK under WI-FI,but throw the error in log :"Task was interrupted [http://xxxxxxxxx]" under GRPS or  EDGE.And image do not load in imageview but load all right when i close my app and open it again. I use this config:
(ImageScaleType.EXACTLY_STRETCHED)
img.setLayoutParams(new LayoutParams(android.view.ViewGroup.LayoutParams.FILL_PARENT, android.view.ViewGroup.LayoutParams.FILL_PARENT));  
img.setScaleType(ScaleType.CENTER_INSIDE);

**Comment by AlbertoMrFz** [comment]
I have the same problem
Any solution?
