### ISSUE TITLE
Image pre-processor and post-processor in Display Options

### ISSUE THREAD

**Issue by nostra13** [nostra13/Android-Universal-Image-Loader#151]
Add possibility pass pre-processor (process Bitmap before caching in memory) and post-processor (process Bitmap after it was cached in memory cache, before it's displaying and do processing on work thread, not UI-thread, as BitmapDisplayer) in Display Options.

**@All_Users** Comment here if you need this feature

**Comment by CapnSpellcheck** [comment]
I will find this useful. As I just discovered that the listener is called on the main thread. And I want to create a second bitmap cropped from the first one  without having to manage my own thread.
