### ISSUE TITLE
Sometimes image is not loading in pager (1.7.0)

### ISSUE THREAD

**Issue by rajendrabohra** [nostra13/Android-Universal-Image-Loader#153]
Thanks for Such a usefull library. I am using loader1.7.0, I found one bug in loading the image in pager view. Sometimes Image not loading, Loading stuck in ImageLoadingListener onLoadingStarted() method. Earlier I was using universal-image-loader-1.5.5-with-src.jar and its working fine. Now I have switched to 1.5.5.

**Comment by sagar2914** [comment]
Hi nostra13,

I am also facing same @rajendrabohra ImageLoder error in android: 4.1.1 .

Logs:

W/dalvikvm: threadid=16: thread exiting with uncaught exception (group=0x40a13300)
E/AndroidRuntime: FATAL EXCEPTION: Thread-84
                  java.lang.ClassCastException: android.support.v7.widget.TintContextWrapper cannot be cast to android.app.Activity
                      at com.foogletech.cdinesh.ImageLoader$PhotosLoader.run(ImageLoader.java:185)

Please Help.

**Comment by AlbertoMrFz** [comment]
I have the same problem as @o-antsiferov 
Any solution?
