### ISSUE TITLE
Add Factory for ImageLoader

### ISSUE THREAD

**Issue by o-antsiferov** [nostra13/Android-Universal-Image-Loader#158]
Say, I want to have book covers and author avatars: for covers one instance of ImageLoader and for avatars the other. These loaders must have different configurations (based on disk size, memore cache size, directory etc).

PS: workaround with protected ImageLoader constructor is not working, because you often use ImageLoader.getInstance() inside your libriary...

**Comment by arcgate-git** [comment]
Could you please tell me how to create multiple instances of image loader. I am using 1.9.3 jar and am stuck in having multiple instances. I have seen #92 link and the o-antsiferov comment seems right. But after that you have not given any solution for it.
