### ISSUE TITLE
Avoiding the fade in effect after a ListView is refreshed

### ISSUE THREAD

**Issue by a85** [nostra13/Android-Universal-Image-Loader#165]
I just started using the universal image loader library and have run into a really annoying problem. Everything loads well for the first shot but if anything changes in the data adapter the library initiates a fade in transition for every image in the list. Even though the images have been loaded already this is quite unnecessary. Is there something I am doing wrong? 

The same applies for stub images. The stub image will be displayed and then the final image which creates this irritating flickering effect every time something in the list changes.

**Comment by MIkeeJY** [comment]
what's the best solution for this problem??anyone help me plz....
