### ISSUE TITLE
De/Encoding for File URI image load problem

### ISSUE THREAD

**Issue by zoularry** [nostra13/Android-Universal-Image-Loader#179]
For an image file: /storage/sdcard0/groupurchase/cache/http%3A%2F%2Fd2.lashouimg.com%2Fzt_mobile_220%2F201211%2F29%2F135417696321262100.jpg

imageLoader tries to load an decoded file path which is incorrect: 

```
02-25 13:20:51.085: E/ImageLoader(27155): java.io.FileNotFoundException: /storage/sdcard0/groupurchase/cache/http:/d2.lashouimg.com/zt_mobile_220/201211/29/135417696321262100.jpg: open failed: ENOENT (No such file or directory)
```

It should keep the encoded string as it is, and read by stream.

The problem is caused by imageloader code below:

``` java
final class ImageLoadingInfo {
...
    public ImageLoadingInfo(String uri, ImageView imageView, ImageSize targetSize, DisplayImageOptions options, ImageLoadingListener listener, ReentrantLock loadFromUriLock) {
        this.uri = Uri.encode(uri, "@#&=*+-_.,:!?()/~'%");
        ...
    }
}
```

**Comment by black-snow** [comment]
Actually this isn't (fully) fixed. I'm using 1.9.3 and get the above error when loading images from sdcard from a directory containing whitespaces (%20).

**Comment by nostra13** [comment]
And what URI string do you pass into ImageLoader?

**Comment by black-snow** [comment]
/sdcard/Android/data/my.package/files/Pictures/directory%20containing%20whitespaces/some_image.jpg

**Comment by nostra13** [comment]
You should pass "/sdcard/Android/data/my.package/files/Pictures/directory containing whitespaces/some_image.jpg"

**Comment by black-snow** [comment]
Aight, that's why you changed it from Uri to String ... 
An overloaded constructor w/ Uri would be great. Error happend due to using Uri.toString() which gives me %20 for whitespaces instead of the whitespace. Or it should be mentioned that %20 (and others) do not work (is it noted somewhere already?)

**Comment by AristoM** [comment]
Replacing white space with %20 is working fine for me

**Comment by hasnain-ahmad** [comment]
Replacing `%20` by space ` ` works fine.
```
String strUri = uri.toString();
strUri = strUri.replace("%20", " ");
```
