### ISSUE TITLE
[1.8.0] memoryCacheExtraOptions affixes the values to the Uri (https)

### ISSUE THREAD

**Issue by chrisjenx** [nostra13/Android-Universal-Image-Loader#188]
I'm using .memoryCacheExtraOptions(512, 512) 
I'm not sure if this is the desired effect but by doing this when performing webrequests it now affixes the size to the end of the image.

https://d3jpl91pxevbkh.cloudfront.net/notha/image/upload/v1360769665/1.png
becomes
https://d3jpl91pxevbkh.cloudfront.net/notha/image/upload/v1360769665/1.png_512x512
Which of course fails loading.

Cheers,
Chris

**Comment by PankovSerge** [comment]
Got this issue with 1.9.3 and https in link. Use AuthImageDownloader from your comment.

**Comment by HarryMMR** [comment]
As suggested, I tried to use AuthImageDownloader to ignore SSL cert error. But from log cat, it seems that AuthImageDownloader override method is not being called and i still get same ssl error. 
I already set ".imageDownloader(new AuthImageDownloader(getApplicationContext(),5000,5000)) " in ImageLoaderConfiguration.
Help please!

**Comment by EricInCD** [comment]
Got this issue with 1.9.4....How to solve it???

**Comment by HarryMMR** [comment]
Have anyone found a fix? I need it ASAP.

**Comment by zhdh2008** [comment]
@nostra13 Your code works well, thanks
