### ISSUE TITLE
How to delete all files in cache folder?

### ISSUE THREAD

**Issue by surfmast3r** [nostra13/Android-Universal-Image-Loader#196]
Greetings, i'm using your UIL library to display image on a listView, i'm trying to create a clear cache button to remove all cached files but it only remove some space and not all.

i have my custom list adapter that use UIL to load images from url and my clear cache button is placed in the main application activity

this is the option code from the adapter class:

``` java
imageLoader = ImageLoader.getInstance();

config = new ImageLoaderConfiguration.Builder(activity.getApplicationContext())

                    .threadPoolSize(5)
                    .threadPriority(Thread.MIN_PRIORITY + 2)
                    .denyCacheImageMultipleSizesInMemory()
                    .memoryCache(new UsingFreqLimitedMemoryCache(2000000)) // You can pass your own memory cache implementation

                    .defaultDisplayImageOptions(DisplayImageOptions.createSimple())
                    .build();

        // Creates display image options for custom display task
        options = new DisplayImageOptions.Builder()
                    .showStubImage(R.drawable.load)
                    .resetViewBeforeLoading()
                    .cacheInMemory()
                    .cacheOnDisc()

                    .build();

        // Initialize ImageLoader with created configuration. Do it once.
        imageLoader.init(config);
        imageLoader.init(ImageLoaderConfiguration.createDefault(activity.getApplicationContext()));
```

and this is the code for the clear cache event in my main class:

``` java
{
@Override
    public boolean onOptionsItemSelected(MenuItem item) {
        switch (item.getItemId()) {
            case R.id.menu_cache: 
                imgLoader =ImageLoader.getInstance();
                imgLoader.getDiscCache().clear();
                                break;

        }
        return true;
    }

}
```

Thanks

**Comment by ansarisufiyan777** [comment]
using this code it will clear your cache

    public static void trimCache(Context context) {
        try {
            File dir = context.getCacheDir();
            if (dir != null && dir.isDirectory()) {
                deleteDir(dir);
            }
        } catch (Exception e) {
            // TODO: handle exception
        }
    }
    public static boolean deleteDir(File dir) {
        if (dir != null && dir.isDirectory()) {
            String[] children = dir.list();
            for (int i = 0; i < children.length; i++) {
                boolean success = deleteDir(new File(dir, children[i]));
                if (!success) {
                    return false;
                }
            }
        }

        // The directory is now empty so delete it
        return dir.delete();
    }

**Comment by manav1994** [comment]
will it delete shared preference file too ?

**Comment by manav1994** [comment]
@ansarisufiyan777 will it delete shared preference file too ?
