### ISSUE TITLE
Ability to Cache and Display Images on a Layout's Background

### ISSUE THREAD

**Issue by kingargyle** [nostra13/Android-Universal-Image-Loader#205]
Currently only ImageViews are supported.  However there are occassions when Layout's background image may change or be set.   I have some code that I put together that uses the UIL memory and disc caches and sets the background image, but it would be nice to have something built in.

If I get time I'll try and submit a patch back, but my hackish way may not be the best way to do it.

**Comment by shihabmi7** [comment]
Simply i want to load an image to a Relative layer background. Which coding part , i should follow/use?
