### ISSUE TITLE
Add ability to cancel a download for a given ImageView

### ISSUE THREAD

**Issue by mpr90** [nostra13/Android-Universal-Image-Loader#22]
I have a ListView with each row containing an ImageView. Not all of the rows have an associated URL for an image so in my adapter, if there is no URL, I assign a default image to the ImageView.

However, when flinging the list quickly such that ImageViews are recycled, I can end up with one of the rows that should have a default image being assigned a downloaded image because I cannot cancel a pending download. I think it goes like this:
1. Start a download on an ImageView with imageLoader.displayImage()
2. ImageView is recycled and for this row, the adapter now assigns a default image because it has no URL
3. Download completes, isConsistent() function returns true, and downloaded image is assigned.

I would like in step 2 to be able to indicate to the ImageLoader that the download associated with an ImageView should not be assigned to the ImageView when it completes please.

Nice library by the way!

**Comment by subbu-mobi** [comment]
i have a list View where user can click to Download and cancel before the OnLoadingComplete gets called.
But when i try to use imageLoader.cancelDisplayTask(view); , the onLoadingCancelled is not called using UIL 1.9.3
