### ISSUE TITLE
RejectedExecutionException error in GridView Scroll

### ISSUE THREAD

**Issue by vrthe1** [nostra13/Android-Universal-Image-Loader#222]
I am having a gridview with 100s of images, when i scroll faster the application crashes with this exeception

```
    03-28 00:13:53.653: E/AndroidRuntime(22094): FATAL EXCEPTION: pool-1-thread-4
    03-28 00:13:53.653: E/AndroidRuntime(22094): java.util.concurrent.RejectedExecutionException: Task com.nostra13.universalimageloader.core.LoadAndDisplayImageTask@4234b478 rejected from java.util.concurrent.ThreadPoolExecutor@41de7df0[Running, pool size = 128, active threads = 128, queued tasks = 10, completed tasks = 398]
    03-28 00:13:53.653: E/AndroidRuntime(22094):    at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:1967)
    03-28 00:13:53.653: E/AndroidRuntime(22094):    at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:782)
    03-28 00:13:53.653: E/AndroidRuntime(22094):    at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1303)
    03-28 00:13:53.653: E/AndroidRuntime(22094):    at com.nostra13.universalimageloader.core.ImageLoaderEngine$1.run(ImageLoaderEngine.java:75)
    03-28 00:13:53.653: E/AndroidRuntime(22094):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
    03-28 00:13:53.653: E/AndroidRuntime(22094):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
    03-28 00:13:53.653: E/AndroidRuntime(22094):    at java.lang.Thread.run(Thread.java:856)
```

Im using the sample code for the gridview.

**Comment by Noam-Modai** [comment]
getting this similar crash : 
java.util.concurrent.RejectedExecutionException: Task com.nostra13.universalimageloader.core.LoadAndDisplayImageTask@43258e90 rejected from java.util.concurrent.ThreadPoolExecutor@42cd7588[Shutting down, pool size = 3, active threads = 1, queued tasks = 0, completed tasks = 2]
       at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:1979)
       at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:786)
       at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1307)
       at com.nostra13.universalimageloader.core.ImageLoaderEngine$1.run(ImageLoaderEngine.java:76)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at java.lang.Thread.run(Thread.java:856)

with the following config :  
ImageLoaderConfiguration config = new ImageLoaderConfiguration.Builder(getApplicationContext()).threadPoolSize(10)
		// default
		.threadPriority(Thread.NORM_PRIORITY - 1)
		// default
		.memoryCacheSize(10 * 1024 * 1024).diskCacheSize(200 * 1024 * 1024)
		.diskCache(new UnlimitedDiscCache(new File(Environment.getExternalStorageDirectory() + "/MOOVZ")))// getFilesDir()))
		.diskCacheFileNameGenerator(new HashCodeFileNameGenerator()).build();
	mImageLoader = ImageLoader.getInstance();
	mImageLoader.init(config);

	mProfileImageOptions = new DisplayImageOptions.Builder().showImageOnLoading(R.drawable.ic_profileimage_blue_feed)
		.showImageForEmptyUri(R.drawable.ic_profileimage_blue_feed).showImageOnFail(R.drawable.ic_profileimage_blue_feed).cacheInMemory(true)
		.cacheOnDisk(true).considerExifParams(true).displayer(new SimpleBitmapDisplayer()).build();
