### ISSUE TITLE
Universal Image Loader and HTTPS (Apache HTTP Component)

### ISSUE THREAD

**Issue by t0mm13b** [nostra13/Android-Universal-Image-Loader#240]
Have noticed, since I use my custom HTTPS SSL Socket factory in my app, using in conjunction with UniversalImageLoader, the loading of the images failed.

**Comment by mehmeth** [comment]
@tapas4git  did you find the answer for your question ? I have the same problem. My code is like;

 Map<String,String> authHeaders = new HashMap<>();
        authHeaders.put("token", LocalStorage.getUserToken(ctx));

        DisplayImageOptions defaults = new DisplayImageOptions.Builder()
                .displayer(new FadeInBitmapDisplayer(300, true, true, false))
                .showImageOnFail(R.drawable.ic_image_fail)
                .showImageForEmptyUri(R.drawable.ic_image_fail)
                .cacheOnDisk(true)
                .cacheInMemory(true)
                .bitmapConfig(Bitmap.Config.RGB_565)
                .extraForDownloader(authHeaders)
                .build();
        ImageLoaderConfiguration.Builder configsBuilder = new ImageLoaderConfiguration.Builder(ctx)

                .imageDownloader(new AuthImageDownloader(ctx))
                .defaultDisplayImageOptions(defaults);
        ImageLoader.getInstance().init(configsBuilder.build());



How can make it https ?
