### ISSUE TITLE
call to OpenGL ES API with no current context (logged once per thread)

### ISSUE THREAD

**Issue by ZuzooVn** [nostra13/Android-Universal-Image-Loader#27]
E/libEGL(22343): call to OpenGL ES API with no current context (logged once per thread)
 D/ShaderProgram(22343): couldn't load the vertex shader!

Hi, i allway see this line

Is it bug?

**Comment by nameispriyank** [comment]
put  android:hardwareAccelerated="true" in </application> of manifest.

**Comment by JustForHappy** [comment]
I find this warning because the following  code in class（ImageSizeUtils）:
GLES10.glGetIntegerv(GL10.GL_MAX_TEXTURE_SIZE, maxTextureSize, 0);
I find an answer to solve this problem：
[http://stackoverflow.com/questions/26985858/gles10-glgetintegerv-returns-0-in-lollipop-only](url)

**Comment by spaul13** [comment]
I am also getting the same error. While decoding a video using ijkplayer and streaming it on unity (using easymovietexture)

I am using **GLES20.glGetBooleanv(GLES20.GL_DEPTH_TEST, abValue, 0);**
@JustForHappy can you please tell me where was the error? I can't open the link.

@nameispriyank I added the line in manifest but it's still not working. Anything else you might suggest?
@nostra13 , you mentioned this as image loader fault, did u find how to get rid of this?

Anyone else has any suggestion please tell me?
