### ISSUE TITLE
Custom headers to HTTP request

### ISSUE THREAD

**Issue by agrebnev** [nostra13/Android-Universal-Image-Loader#340]
Hi

I would like to use your library to download images from social networks. However for example Twitter requires additional Authorization header to http requests. 

I looked at the possibility to extend BaseImageDownloader however it can be specified only for global singleton config. But I need to add different headers to different requests. 

Please add such functionality. Thanks in advance.

**Comment by SaifurRahmanMohsin** [comment]
Why is this issue closed? I tested this on v1.9.4 and it still persists. The CustomImageDownloader class never gets called.

**Comment by VanditPatel** [comment]
I am facing same issue - createConnection method in CustomImageDownaloder class not call.

**Comment by liruizhuang** [comment]
befor call **ImageLoader.getInstance().init(config)**,you should call ImageLoader.getInstance().**destroy() ** first.
