### ISSUE TITLE
loading images progressively/interlaced

### ISSUE THREAD

**Issue by hielkehoeve** [nostra13/Android-Universal-Image-Loader#369]
All of our images are progressive images (jpg) or interlaced images (png). It would be cool to allow for these images to be displayed asap, so that users aren't looking at placeholders until the images is downloaded.

http://www.codinghorror.com/blog/2005/12/progressive-image-rendering.html

**Comment by titanseason** [comment]
If you have find voud a way to implement this?

**Comment by somghosh** [comment]
Does UIL support progressive image loading now?

**Comment by hielkehoeve** [comment]
This project is dead

**Comment by nostra13** [comment]
Yep

**Comment by SohailZahidGit** [comment]
Any new link for Interlacing in android?
