### ISSUE TITLE
Encrypt file cache directory or cached images

### ISSUE THREAD

**Issue by sourabhdeshpande** [nostra13/Android-Universal-Image-Loader#370]
I am using the file cache to store the images locally. But i want to store the images in encrypted form , so that these images can not be seen through any other app such as gallery. Only my application should be able to read the images that are cached using file cache. Please suggest any way to achieve this. Can we use CipherInputStream and CipherOutPutStream for reading and writing encrypted files?

**Comment by mauriciotogneri** [comment]
@grumoon I ended up having the same solution than you but I don't want to store the decrypted information in a temporary file. Did you solve the problem?
