### ISSUE TITLE
Cannot display some local files with a space in their name

### ISSUE THREAD

**Issue by markuspfeiffer** [nostra13/Android-Universal-Image-Loader#371]
I'm loading images from the local storage using the following code:

```
if (file.exists() && ContentType.isImage(file)) {
    final String uri = Uri.fromFile(file).toString();
    ImageLoader.getInstance().displayImage(uri, imageView);
}
```

This fails with the following exception:

```
/storage/emulated/0/.../ad%20(1).jpg: open failed: ENOENT (No such file or directory)
java.io.FileNotFoundException: /storage/emulated/0/.../ad%20(1).jpg: open failed: ENOENT (No such file or directory)
```

// path manually truncated, due to length

It looks like the file name extracted from the URL does not decode the %20 to " ".

**Comment by zoumy** [comment]
@Dcodechef @markuspfeiffer I got the same issue,I tried to use Uri.decode(),but  java.io.FileNotFoundException: /storage/emulated/0/storage/emulated/0/Pictures/Screenshots/Screenshot_2015-03-12-17-31-02.png

My code:
ImageLoader.getInstance().displayImage(Uri.decode(data.get(position).toString()),holder.imageView);
I couldn't show my local images to gridView.

**Comment by markuspfeiffer** [comment]
The Uri.decode() is only really needed for local files with a blank in 
their name. In your case the issue seems to be a malformed path, look at 
the start of your path:

"/storage/emulated/0/storage/emulated/0"

There seems to be an issue with the code that creates your path. For 
some reason the "/storage/emulated/0" is added twice.

**Comment by wangduanqing5945** [comment]
I have same problem when path contains chinese.
