### ISSUE TITLE
Can't load image if URL without extension

### ISSUE THREAD

**Issue by nzakharchenko** [nostra13/Android-Universal-Image-Loader#375]
If I have ULR, that doesn't contain file extension on the end (e.g. http://encrypted.google.com/books/images/frontcover/y3TrbpTK3zoC?fife=h120-rw) - image not loaded.

In LogCat I see such error message:
Image can't be decoded [http://encrypted.google.com/books/images/frontcover/y3TrbpTK3zoC?fife=h120-rw_180x180]

Also, for some reasons, part '_180x180' is added in the end of URL, why?

**Comment by joshua-meng** [comment]
@nzakharchenko So how to load encrypted URL on Android at last?

**Comment by nzakharchenko** [comment]
@joshua-meng I'm not sure that I could remember now what was this issue about. Sorry, could not help you with this question.

**Comment by joshua-meng** [comment]
@nzakharchenko Thanks all the same.
