### ISSUE TITLE
How can I get cache image path for particular URL..

### ISSUE THREAD

**Issue by bhavesh-hirpara** [nostra13/Android-Universal-Image-Loader#420]
I can not process Bitmap in webview So I want that cache image path in onloadingComplated or else where .... I am getting bitmap but I have to save in memory card temporary and will have to load through that path. 

suppose i am loading from http://www.ricoh.com/r_dc/cx/cx1/img/sample_04.jpg. with cache on disc configuration and If i want cached image path of this url then how can I get??

I want to display image in webview. webview will not cahe my image. I want to cache image with image loader and want to display in webview.
Can you provide cached image path also??

**Comment by hodaz** [comment]
Use full package name
com.nostra13.universalimageloader.utils.DiskCacheUtils.findInCache()
