### ISSUE TITLE
Some images are displayed wrong in GridView

### ISSUE THREAD

**Issue by frankred** [nostra13/Android-Universal-Image-Loader#430]
First I want to say thank you Sergey for this awesome project!

So here I present you my problem with an example application:

I have six images showing numbers. All images are numbered consecutively from 1 to 6.
Sometimes all images are displayed correctly and sometimes some of them are displayed wrong.

The right order of the images is: 1, 2, 3, 4, 5, 6

Here is the video of the bug: http://www.youtube.com/watch?v=8a9zb3PQTPY 
You can download it here as eclipse project: http://share.mynotiz.de/OnlineImageViewer-with-Video%20Android-Universal-Image-Loader.zip

Am I doing something wrong or is it a bug in the universal-image-loader?

Thanks for reading...

Frank Roth

**Comment by Manbec** [comment]
@nostra13  you just saved my day
