### ISSUE TITLE
ImageLoader inside RemoteViewsFactory ?

### ISSUE THREAD

**Issue by azerto00** [nostra13/Android-Universal-Image-Loader#441]
Hello,

I started today to use your Android Universal Image Loader which is very very nice !
Thank you for sharing this !

I know that its is possible to use AUIL in an android widget project inside the Provider class but I'm trying to load multiples image inside a ListView (itself inside the widget).

So i thought about adding the following code inside my RemoteViewsFactory :

``` java
    @Override
    public RemoteViews getViewAt(int position)
    {
        final RemoteViews row = new RemoteViews(ctxt.getPackageName(), R.layout.row);
                String url = url depending on the position
        m_imgLoader.loadImage(url, new SimpleImageLoadingListener()
        {
            @Override
            public void onLoadingComplete(String imageUri, View view, Bitmap loadedImage)
            {
                row.setImageViewBitmap(R.id.ivPoster, loadedImage);
            }
        });
    }
```

But I'm getting "Can't create handler inside thread that has not called Looper.prepare()" which if I do understand well tells me that I'm not on an UI thread, so I can't use setImageViewBitmap.

Do you know an alternative to this problem ?
Thank you for your time !

**Comment by pristalovpavel** [comment]
My ListView with about 15 elements on fast scroll crashes launcher with java.lang.OutOfMemoryError. I'm using cacheInMemory, cacheOnDisk and imageScaleType(ImageScaleType.EXACTLY).
