### ISSUE TITLE
Bitmap too large to be uploaded into a texture

### ISSUE THREAD

**Issue by MikeWallaceDev** [nostra13/Android-Universal-Image-Loader#508]
Hi @nostra13 I'm getting a "Bitmap too large to be uploaded into a texture (2592x1944, max=2048x2048)" as well and I'm using 1.9.1. I can load the image in landscape but not in portrait (using the same layout)

In my Application: 

``` java
      ImageLoaderConfiguration config = new ImageLoaderConfiguration.Builder(getApplicationContext()).build();
      ImageLoader.getInstance().init(config);
```

In my Activity: 

``` java
   ImageLoader         m_imageLoader = ImageLoader.getInstance();
   DisplayImageOptions m_options     = new DisplayImageOptions.Builder()
         .showImageOnLoading(R.drawable.image_loading) // resource or drawable
         .showImageForEmptyUri(R.drawable.image_error) // resource or drawable
         .showImageOnFail(R.drawable.image_error) // resource or drawable
         .build();
```

**Comment by balintfarago** [comment]
I can confirm that the bug 'Bitmap too large to be uploaded into a texture (4128x2322, max=4096x4096)' is still present in version 1.9.3.
Btw, after upgrading from 1.9.1 to 1.9.3 I had to change all listeners and some images are displayed incorrectly. I am going back to 1.9.1 until this bitmap issue is solved. Other than that, fantastic library!

**Comment by kongbt** [comment]
Hi nostra13,
how to automatically switch modes ImageScaleType.NONE_SAFE if i get
Bitmap too large to be uploade?

On Wed, Dec 17, 2014 at 1:06 PM, Sergey Tarasevich <notifications@github.com
> wrote:

> If you use DisplayImageOptions.imageScaleType(ImageScaleType.NONE) then
> you can get Bitmap too large to be uploaded into a texture.You should use
> it only if you sure your images are not too large. If so then you should
> scale Bitmap yourself to maximum available texture size or you can use
> ImageScaleType.NONE_SAFE instead.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nostra13/Android-Universal-Image-Loader/issues/508#issuecomment-67281047>
> .
>



-- 
Thanks and best regards.

CHIPPOO, JSC

BUI THANH CONG
Mobile: 0963848999
E-Mail: kongbt@chippoo.com, kongbt@gmail.com
Website: http://mobiway.vn
