### ISSUE TITLE
Multiple calls with the same URL only gets 1 answer

### ISSUE THREAD

**Issue by cdongieux** [nostra13/Android-Universal-Image-Loader#510]
Hi,

First of all, thank you so much for all your remarkable work, your lib really rocks!

I'm currently intregrating it in my project, and I found something strange. See the following snippet:

``` java
    private class Networker {
        void getStuff(String source) {
            ImageLoader.getInstance().loadImage(source, new SimpleListener());
        }

        private class SimpleListener extends SimpleImageLoadingListener {
            @Override
            public void onLoadingComplete(String imageUri, View view,
                    Bitmap loadedImage) {
                Log.d("UIL", "onLoadingComplete: "+imageUri);
            }
        }
    }

    private void func() {
        DisplayImageOptions defaultOptions = new DisplayImageOptions.Builder()
                .cacheInMemory(false).cacheOnDisc(false).build();
        ImageLoaderConfiguration config = new ImageLoaderConfiguration.Builder(
                getApplicationContext()).defaultDisplayImageOptions(
                defaultOptions).build();
        ImageLoader.getInstance().init(config);

        Networker n = new Networker();
        n.getStuff("http://www.google.fr/images/srpr/logo11w.png");
        n.getStuff("http://www.google.fr/images/srpr/logo11w.png");
        n.getStuff("http://www.google.fr/images/srpr/logo11w.png");
    }
```

When calling method func(), "OnLoadingComplete" is only called once. What am I missing?

Thanks in advance.

Regards,
Christophe.

**Comment by Frank1234** [comment]
And what if you do not know the target size?

**Comment by Yonfu** [comment]
You can take the absolute width of the display in pixels. See method 
```
    loadImage(String uri, ImageSize targetImageSize, DisplayImageOptions options,
			ImageLoadingListener listener, ImageLoadingProgressListener progressListener)
        checkConfiguration();
	if (targetImageSize == null) {
	    targetImageSize = configuration.getMaxImageSize();  
	}
        ...
```
Method getMaxImageSize
```
        ImageSize getMaxImageSize() {
		DisplayMetrics displayMetrics = resources.getDisplayMetrics();

		int width = maxImageWidthForMemoryCache;
		if (width <= 0) {
			width = displayMetrics.widthPixels;
		}
		int height = maxImageHeightForMemoryCache;
		if (height <= 0) {
			height = displayMetrics.heightPixels;
		}
		return new ImageSize(width, height);
	}
```

**Comment by Frank1234** [comment]
Thank you.

**Comment by nebyan** [comment]
Hi I also had the same problem have wrote custom class it use Imageloader find good solution.

public class MyMusicImageLoader {

    public static MyMusicImageLoader myMusicImageLoader;
    public ImageLoader imageLoader;
    public Map<String,MImageLoader> mImageLoaderMap = new HashMap<String, MImageLoader>();

    public static MyMusicImageLoader getInstance(){
        if(myMusicImageLoader==null)
            myMusicImageLoader = new MyMusicImageLoader();
        return myMusicImageLoader;
    }

    public MyMusicImageLoader(){
        imageLoader = ImageLoader.getInstance();
    }

    public void loadImage(final String url,ImageLoadingListener imageLoadingListener){

        MImageLoader mImageLoader = mImageLoaderMap.get(url);
        if(mImageLoader==null){
            mImageLoader = new MImageLoader(url);
            mImageLoader.addImageLoadingListener(imageLoadingListener);
            mImageLoaderMap.put(url,mImageLoader);
            imageLoader.loadImage(url, new SimpleImageLoadingListener(){
                @Override
                public void onLoadingComplete(String imageUri, View view, Bitmap loadedImage) {
                    setAllMImageLoader(url,loadedImage);
                }
            });
        }else{
            mImageLoader.addImageLoadingListener(imageLoadingListener);
        }

    }

    public void setAllMImageLoader(String url, Bitmap bitmap){
        MImageLoader mImageLoader =  mImageLoaderMap.remove(url);
        ArrayList<ImageLoadingListener> imageLoadingListeners = mImageLoader.imageLoadingListeners;

        for(int i=0; i<imageLoadingListeners.size(); i++){
            ImageLoadingListener imageLoadingListener = imageLoadingListeners.get(i);
            imageLoadingListener.onLoadingComplete("",null,bitmap);
        }

        imageLoadingListeners.clear();

    }

    class MImageLoader{
        String imageUrl;
        ArrayList<ImageLoadingListener> imageLoadingListeners = new ArrayList<ImageLoadingListener>();
        MImageLoader(String imageUrl){
            this.imageUrl = imageUrl;
        }

        void addImageLoadingListener(ImageLoadingListener imageLoadingListener){
            imageLoadingListeners.add(imageLoadingListener);
        }
    }
}

**Comment by PoetKing** [comment]
https://mp.weixin.qq.com/s/dFdKg5CDVUXktQiE9p9Kcg

**Comment by PoetKing** [comment]
Maybe it could help some people：
https://mp.weixin.qq.com/s/dFdKg5CDVUXktQiE9p9Kcg
