### ISSUE TITLE
Refresh Cache

### ISSUE THREAD

**Issue by lorensiuswlt** [nostra13/Android-Universal-Image-Loader#515]
I know caching feature is nicely support by this library, but in my implementation i need to replace the old cache with the latest one downloaded from the same url. So, everytime i call imageLoader.displayImage(), if cache exist it will display the cache but at the same time it also downloading from the image url to replace it with the latest because the image from the same url is changing frequently (eg: from CCTV images).

**Comment by CsabaMiomni** [comment]
Thx for closing this without leaving any tips. :(
