### ISSUE TITLE
Gif support

### ISSUE THREAD

**Issue by o-antsiferov** [nostra13/Android-Universal-Image-Loader#518]
It would be great if UIL will support GIF animation

**Comment by brucetoo** [comment]
can someone tell me when i use Universal-Image-Loader to download a gif photos,After downloading,it will like this "@Override
                    public void onLoadingComplete(String imageUri, View view, Bitmap loadedImage) {",I just want to ask it Gif's cache already in Memory?Absolutely,i Have already set DisplayImageOptions,like " .cacheInMemory(true)
                .cacheOnDisk(true)"!  But I find when I use "ImageLoader.getInstance().getDiskCache().get(src).getAbsolutePath()"  to get cache in callback  method onLoadingComplete(...),It sometimes actually Null, Why ? Somebody help~

**Comment by andrejvanderzee** [comment]
Glide does support animated GIF

**Comment by VihaanVerma89** [comment]
would be great if it supports gif +1
