### ISSUE TITLE
Can't load image from Content Provider

### ISSUE THREAD

**Issue by MikeWallaceDev** [nostra13/Android-Universal-Image-Loader#539]
Hello,

I'm having a weird problem. I have two apks, one is a Content Provider and the other consumes the data. The following code in the consumer does not work:

``` java
imageLoader.displayImage("content://com.risesoftware.coloroos_animals/assets/aa.png", imgvw_page);
```

The error is : 

```
E/ImageLoader﹕ Image can't be decoded [content://com.risesoftware.coloroos_animals/assets/aa.png_1000x1000]
```

but the following code DOES work : 

``` java
Uri theUri = Uri.parse("content://com.risesoftware.coloroos_animals/assets/aa.png");
InputStream inputStream = null;
inputStream = m_context.getContentResolver().openInputStream(theUri);
Bitmap bitmap = BitmapFactory.decodeStream(inputStream);
imgvw_page.setImageBitmap(bitmap);
```

I looked through BaseImageDownloader and the code is virtually identical.

**Comment by ricardolonga** [comment]
Hello!

I have the same problem!

My simple code:

ImageLoader.getInstance().displayImage("http://sanrebeauty.com.br/img/uploads/548668d89d3926.21514457.jpg", new ImageView(this));

UIL configurations:

 new ImageLoaderConfiguration.Builder(context).threadPriority(Thread.NORM_PRIORITY - 2).tasksProcessingOrder(QueueProcessingType.LIFO).writeDebugLogs().threadPoolSize(1).imageDecoder(new NutraBaseImageDecoder(true)).defaultDisplayImageOptions(DisplayImageOptions.createSimple()).build();

In my SII with Android 4.4.4 perfectly works, but in my Tab 3 Lite with Android 4.2.2 the error is: 

01-18 18:57:31.843  22160-22174/br.sanre D/skia﹕ --- decoder->decode returned false
01-18 18:57:31.843  22160-22174/br.sanre E/ImageLoader﹕ Image can't be decoded [http://sanrebeauty.com.br/img/uploads/548668d89d3926.21514457.jpg_600x1024]

I tried with the two examples of NutraBaseImageDecoder  and without. 

Any idea?

**Comment by MikeWallaceDev** [comment]
Hello, it's me again :)

I'm still trying to get this to work. Same conditions, same error.

I've traced the code all the way to the native call. I have no clue still why this doesn't work. UIL is able to open the stream, it's able to read the stream and determine the size of the image. Everything seems fine. The only thing the I think can be wrong is the config parameters that are passed into the nativeDecodeStream method.  So I'm attaching these images : that show all of the config just before the call.

I hope this helps...

-MIke

![screenshot_070](https://cloud.githubusercontent.com/assets/5375835/6261187/7be6ac9e-b7b9-11e4-80e5-9ca00d234084.png)

![screenshot_071](https://cloud.githubusercontent.com/assets/5375835/6261188/8498d4d4-b7b9-11e4-9ab5-52970647af6b.png)

**Comment by MikeWallaceDev** [comment]
Another update, this morning I decided to compare the above values with the native call.  The big difference that I see is that the opts value is null in the native call.
I wanted to try that out in my project, cloned the UIL source, but it doesn't seem to be gradle ready, so I wasn't able to try.  Can someone do a quick try with a null opts?  Or tell me how to integrate the source code into my project?

**Comment by hdering** [comment]
hi,

I had the same problem with "Image can't be decoded". My problem was, I had to authenticate.

I created a new class:

```javascript
public class CustomImageDownloader extends BaseImageDownloader {

    String TAG = "CustomImageDownloader";

    public CustomImageDownloader(Context context) {
        super(context);
    }

    @Override
    protected HttpURLConnection createConnection(String url, Object extra) throws IOException {

        String credentials = "username" + ":" + "password";

        String base64EncodedCredentials = Base64.encodeToString(credentials.getBytes(), Base64.NO_WRAP);

        HttpURLConnection conn = super.createConnection(url, extra);

        conn.setRequestProperty("Authorization", "Basic " + base64EncodedCredentials);

        return conn;
    }
}
```

and added the following:
```javascript
        ImageLoaderConfiguration config = new ImageLoaderConfiguration.Builder(mContext)
                ...
                .imageDownloader(new CustomImageDownloader(mContext))
                ...
                .build();
```

**Comment by lokendrayadav** [comment]
Please some one tell  ,I am having video's URL , so i want to so them in thumbnail view, mean i want to get thumbnail from videos using Android-Universal-Image-Loader ,and one more thing pardon my english

**Comment by Ratnesh-K** [comment]
Hello frodberserk 
can you please tell me how you fix these problem??
@frodberserk

**Comment by frodberserk** [comment]
@Ratnesh-K I already posted that there was an issue in the image. It was CMYK and not RGB. So, I changed the configuration of image from CMYK and RGB, and it fixed the issue. I guess there are many solutions posted above, so, give them a try :)

**Comment by master11360** [comment]
I have the same problem. Any update for it?

**Comment by liyuqiang01** [comment]
Reduce the size of the picture to solve the problem
