### ISSUE TITLE
ImageLoader add screen size in the end of url 

### ISSUE THREAD

**Issue by kioltk** [nostra13/Android-Universal-Image-Loader#563]
Hello Sergey, my issue is very strange.
I'm trying to download a lot of svg images, but Loader adds the screen size in the end of url, sooo it cant find any images using this url and returns null.
The stragneness is the loader doesn't corrupt all my urls, but I cant understand how he selects what to corrupt.
Here what I have in my log
Image can't be decoded [http://upload.wikimedia.org/wikipedia/commons/b/b3/Africa_independence_dates.svg_768x1184]
I debugged my application till the moment I call Loader, so I am sure that it isn't my mistake. 
Maybe I forgot to set any parameter in config?

**Comment by manideepl** [comment]
I've exactly the same problem. So how do I resolve this?

**Comment by MageshkumarU** [comment]
@manideepl Read the Useful Info Again.

Log shows the URL+Target Size. That is not your exact url. Its only for memory cache not used for requests.
