### ISSUE TITLE
How to really disable scaling?

### ISSUE THREAD

**Issue by virusman** [nostra13/Android-Universal-Image-Loader#590]
Since 1.9.1 ImageScaleType.NONE doesn't completely disable scaling - the image will still be scaled down to the maximum texture size.
I'm using UniversalImageLoader just for loading, and don't pass the bitmap to ImageView. How do we get the full, unscaled image?

**Comment by daisydeepa** [comment]
Even if i use ImageScaleType.NONE it got scaled and streched. Please let me know how to resolve it

**Comment by nostra13** [comment]
`android:scaleType` for you.

**Comment by daisydeepa** [comment]
Thanks for your reply.
I have used scale type as center crop in imageview.  And in image loader
configuration. Tried with NONE as a scale type too.  But the image was
scaled and gave a stretch effect in Rounded image view. :(

**Comment by asielgil88** [comment]
same that daisydeepa , anybody found a solution?
