### ISSUE TITLE
loadImageSync return null

### ISSUE THREAD

**Issue by saltcoffee** [nostra13/Android-Universal-Image-Loader#666]
hello, guys. 
why when i use "loadImageSync" , it returned null.

``` java
ImageLoader imageLoader = ImageLoader.getInstance();
Bitmap bitmap =  imageLoader.loadImageSync("http://thumb.dongtw.com/?width=240&height=180&url=http%3A%2F%2Fs2.imgs.cc%2Fimg%2Fjdr4HwY.jpg");
imageView.setImageBitmap(bitmap);
bitmap is null, 
```

but when i use 

``` java
imageLoader.displayImage("http://thumb.dongtw.com/?width=320&height=180&url=http%3A%2F%2Fs2.imgs.cc%2Fimg%2Fjdr4HwY.jpg", imageView);
```

it worked well. so why this happened, thx, :)

**Comment by dors** [comment]
Same here. V1.9.3.
Calling:
bitmap = ImageLoader.getInstance().loadImageSync(iconUrl);

In an IntentService. The intent service is triggers due to an alarm.

The behaviour is inconsistent - sometimes I get the bitmap, sometimes I get null (it is hard to reproduce getting 'null', I mainly see users getting it in Google Analytics).

**Comment by kiruwka** [comment]
Same here on HTC One: Same image loads fine most of the time, but in about 10% cases, when I load multiple images in same async task one by one, it retuns null :
Bitmap image = ImageLoader.getInstance().loadImageSync(uri, mThumbImageSize, mDisplayImageOptions);
As mentioned, this code runs in AsyncTask.

**Comment by kiruwka** [comment]
Any news regarding this, or any workaround ? It keeps giving me problems, last reported device in production was Galaxy S3 Mini (GT-I8190) Android 4.1.2 (I8190XXANI4)

Should I just abandon using loadImageSync and stick with async version : loadImage ?

**Comment by vernazza** [comment]
Same problem. I load files from assets ("assets://image.png"), so it seems it's not related to networking.

**Comment by Zartha** [comment]
I am also facing the same problem.  I am calling loadImageSync in onCreate of an Activity. Please help. 

Thanks

**Comment by JackSparrow2015** [comment]
I find if I have a cache, loadImageSync will work.

**Comment by asafchet** [comment]
I had the same issue as described here, i solved it by wrapping the loadImageSync method with a synchronized object.
I had a case where there is a chance the method was called from two different threads simultaneously. looks like it solved the problem.

**Comment by eyyoung** [comment]
NonViewAware getId from imageUri,when two task with the same url,it will cancel the old task and this method returns null.I have done some fix,and it work for me.

[https://gist.github.com/eyyoung/418b81ddab5114041c52](url)

**Comment by mlostekk** [comment]
same here with 1.9.5.. sometimes it returns null. running in an asynctask.

It looks like its a bug when the image has been used in an ImageAware before. I am loading it to an cache, then setting it to an ImageView.
The log looks like this

`ImageAware is reused for another image. Task is cancelled. [file:///mnt/sdcard/Download/stuff/8.png_500x400]`

even though i always use a call like this

ImageLoader.getInstance().loadImageSync("file://" + path, new ImageSize(aspectW, aspectH), options)

with display option

`isplayImageOptions         options        = optionsBuilder.imageScaleType(ImageScaleType.NONE_SAFE).build();`

and init options

```
ImageLoaderConfiguration.Builder c = new ImageLoaderConfiguration.Builder(context).denyCacheImageMultipleSizesInMemory()
                                                                                          .diskCacheSize(32 * 1024 * 1024)
                                                                                          .tasksProcessingOrder(QueueProcessingType.LIFO)
                                                                                          .writeDebugLogs();
```
