### ISSUE TITLE
How to get cache image file path

### ISSUE THREAD

**Issue by xuechinahb** [nostra13/Android-Universal-Image-Loader#673]
I have a viewpager which is filled with images，now I want to get UIL cache image.
Refer to my comments of issue #508 , UIL can't resolve my requirement. I use ListView to load images, viewpager to display original image, viewpager has 9 items. So, when instantiate viewpager item , I use AsyncTask to query cache image and decode image file. 
I have read issue #420 , try below three method.

``` java
File file = DiscCacheUtil.findInCache(url, imageloader.getDiscCache());

File file = imageloader.getDiscCache().get(url);
String path = com.nostra13.universalimageloader.core.download.ImageDownloader.Scheme.FILE.wrap(url);
```

 But, I can't get all files successfully everytime, always only two files. If switch viewpager back and forth, all files is null or not exist, viewpager doesn't  display any content.

**Comment by kiran-pathe** [comment]
@xuechinahb 
I did not understood why you are using getAbsoluteFile() method as it returns File object not String object.

Try this one
---------------

 File file = ImageLoader.getInstance().getDiskCache().get(<your_url_link>)
String path = file.getAbsolutePath();

**Comment by Ankurjain30** [comment]
how can i set this path to imageview now?
