### ISSUE TITLE
Multiple calls to same URI gets cancelled

### ISSUE THREAD

**Issue by niteshkhatri** [nostra13/Android-Universal-Image-Loader#694]
Hi. I am using loadImage method to get the image from URI. When I call the same URI more than one times, it cancels the call. I found this link https://github.com/nostra13/Android-Universal-Image-Loader/issues/510 .

In this link, you mentioned that we should use display image instead of loadImage and should use ImageNonViewAware as the ImageAware.

Below is my code:

``` java
    for(int i=0; i<3; i++) {
        ImageSize imageSize = new ImageSize(size, size);
        ImageNonViewAware imageAware = new ImageNonViewAware(imageSize, ViewScaleType.CROP);
        ImageLoader.getInstance().displayImage(imageURI, imageAware, new SimpleImageLoadingListener() {
            @Override
            public void onLoadingComplete(String imageUri, View view, Bitmap loadedImage) {
                bitmaps[Counter] = loadedImage;
                Counter++;
                if(Counter == 3) {
                    allBitmap = receivedAllImages(bitmaps);
                    imageView.setImageBitmap(allBitmap);
                }
            }
        });
    }
```

Code explanation: 
I have a list of three rows. I have three URIs a, b and c. All of them give me a Bitmap.

size - size of the image
imageURI - URI to get the Bitmap
Counter - stores the number of images I have received
bitmaps[] - stores the Bitmaps I receive from imageURIs
receivedAllImages() - modifies the Bitmaps I have received and give me on final Bitmap
allBitmap - the final Bitmap that should be visible in the list
imageView - ImageView to set the Bitmap

 For the first row I have to call URIs a, b and c and after all these images are received, I want to set the allBitmap in the imageView.
For the second row I have to call URIs a and b and after all these images are received, I want to set the allBitmap in the imageView.
For the third row I have to call URI a and after the image is received, I want to set the allBitmap in the imageView.
Finally, I have three final Images for three rows.

Earlier I was using loadImage method to get the Bitmaps but since I am calling same URI more than once, my call was getting cancelled. Then I used displayImage method to overcome this.

Now my problem is, the image of the first row fluctuates between the three final Images. At first it shows the image of third row, then changes to the image of 2nd row and finally shows the correct image. 

Why is this happening? How can I solve this problem? Is there any other way to solve this? Or is there a way to use the loadImage but NOT cancel the URI calls?

**Comment by PoetKing** [comment]
Maybe it could help some people：
https://mp.weixin.qq.com/s/dFdKg5CDVUXktQiE9p9Kcg
