### ISSUE TITLE
scaleType seems to be ignored

### ISSUE THREAD

**Issue by emanuelef** [nostra13/Android-Universal-Image-Loader#70]
Hi, if I change item_list_image.xml in the example into:    

<ImageView
        android:id="@+id/image"
        android:layout_width="172dip"
        android:layout_height="72dip"
        android:adjustViewBounds="true"
        android:contentDescription="@string/descr_image"
        android:scaleType="centerCrop" />

the images are not rounded.
Seems scaleType breaks something.

**Comment by ChulkovNexus** [comment]
me too

**Comment by feng88724** [comment]
Has this issue been solved?

**Comment by Palakppatel** [comment]
I am also facing same issue with RoundedBitmapDisplayer.
Any Solution?
