### ISSUE TITLE
Exception load image from https

### ISSUE THREAD

**Issue by pandabo1985** [nostra13/Android-Universal-Image-Loader#713]
when loading image from url of https,I find an exception.
how to deal this excepthion like javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

thanks.

**Comment by HarryMMR** [comment]
As suggested, I tried to use AuthImageDownloader to ignore SSL cert error. But from log cat, it seems that AuthImageDownloader override method is not being called and i still get same ssl error. 
I already set ".imageDownloader(new AuthImageDownloader(getApplicationContext(),5000,5000)) " in ImageLoaderConfiguration.
Help please!
