### ISSUE TITLE
android universal image loader not caching or saving image

### ISSUE THREAD

**Issue by nomizodiac** [nostra13/Android-Universal-Image-Loader#733]
http://stackoverflow.com/questions/25424103/android-universal-image-loader-not-caching-or-saving-image

**Comment by MathanChinna** [comment]
This will Help you to load imageurl using universal imageloader it will give status for imageurl is start to Loading , Completed or failed and request is cancel status also providing.I hope it may help you.. 

     public void ImageLoaderListener(String url){
   
            imageLoader.loadImage(url,new ImageLoadingListener(){
                @Override
                public void onLoadingStarted(String imageUri, View view) {
                    Log.e("tag", "onLoadingStarted");
                }

                @Override
                public void onLoadingFailed(String imageUri, View view, FailReason failReason) {
                    Log.e("tag", "onLoadingFailed");
                }
                @Override
                public void onLoadingComplete(String imageUri, View view, Bitmap loadedImage) {
                    Log.e("tag", "onLoadingComplete");
                    imageView.setImageBitmap(loadedImage);
                }
                @Override
                public void onLoadingCancelled(String imageUri, View view) {
                    Log.e("tag", "onLoadingCancelled");
                }
            });
        }
if you like to cache the image add this below functions... But to initiate on create because its very highly ..

     ImageLoaderConfiguration config = new ImageLoaderConfiguration.Builder(getApplicationContext())
                .defaultDisplayImageOptions(DisplayImageOptions.createSimple())
                .build();

        imageLoader = imageLoader.getInstance();

        if (!imageLoader.isInited()) {
            imageLoader.init(config);
        }
        defaultOptions = new DisplayImageOptions.Builder()
                .cacheInMemory(true)
                .cacheOnDisc(true)
                .build();

Then you will add that ImageLoadingListener() function...

    public void ImageLoaderListener(String url){
      imageLoader.loadImage(url, defaultOptions, new ImageLoadingListener() {
