### ISSUE TITLE
PauseOnScrollListener for RecyclerView

### ISSUE THREAD

**Issue by RaffiOhanian** [nostra13/Android-Universal-Image-Loader#799]
Im trying to implement the PauseOnScrollListener for the new RecyclerView but the PauseOnScrollListener extends AbsListViewOnScroll and the RecyclerView is a fragment so it does not imply to its onScrollListener.

**Comment by shalom365** [comment]
Thank you very much

**Comment by pinkApple** [comment]
i want  change to resume state before idle state when is going to stop .. how can i  implement it?

**Comment by spartacus777** [comment]
I would suggest little bit modified version of scroll listener - 

    public class NewPauseOnScrollListener extends RecyclerView.OnScrollListener {

    private ImageLoader imageLoader;

    private final boolean pauseOnScroll;
    private final boolean pauseOnSettling;
    private final RecyclerView.OnScrollListener externalListener;

    private boolean stopped = false;

    public NewPauseOnScrollListener(ImageLoader imageLoader, boolean pauseOnScroll, boolean pauseOnSettling) {
        this(imageLoader, pauseOnScroll, pauseOnSettling, null);
    }

    public NewPauseOnScrollListener(ImageLoader imageLoader, boolean pauseOnScroll, boolean pauseOnSettling,
                                    RecyclerView.OnScrollListener customListener) {
        this.imageLoader = imageLoader;
        this.pauseOnScroll = pauseOnScroll;
        this.pauseOnSettling = pauseOnSettling;
        externalListener = customListener;
    }

    @Override
    public void onScrollStateChanged(RecyclerView recyclerView, int newState) {
        Log.v("SCR", "onScrollStateChanged");
        switch (newState) {
            case RecyclerView.SCROLL_STATE_IDLE:
                Log.d("SCR", "onScrollStateChanged :  + SCROLL_STATE_IDLE");
                imageLoader.resume();
                stopped = false;
                break;
            case RecyclerView.SCROLL_STATE_DRAGGING:
                Log.d("SCR", "onScrollStateChanged :  + SCROLL_STATE_DRAGGING");
                if (pauseOnScroll) {
                    imageLoader.pause();
                    stopped = true;
                } else if (stopped){
                    imageLoader.resume();
                    stopped = false;
                }
                break;
            case RecyclerView.SCROLL_STATE_SETTLING:
                Log.d("SCR", "onScrollStateChanged :  + SCROLL_STATE_SETTLING");
                if (pauseOnSettling) {
                    imageLoader.pause();
                    stopped = true;
                } else if (stopped){
                    imageLoader.resume();
                    stopped = false;
                }
                break;
        }
        if (externalListener != null) {
            externalListener.onScrollStateChanged(recyclerView, newState);
        }
    }

    @Override
    public void onScrolled(RecyclerView recyclerView, int dx, int dy) {
        Log.i("SCR", "onScrolled + dx:"+dx+"  dy:"+dy);
        if (externalListener != null) {
            externalListener.onScrolled(recyclerView, dx, dy);
        }
    }
}

**Comment by julianguyen** [comment]
Was this ever updated to support RecyclerView?

**Comment by nostra13** [comment]
I don't think so. UIL isn't maintained anymore.
