### ISSUE TITLE
Cannot load image from the same uri twice

### ISSUE THREAD

**Issue by ddmytrenko** [nostra13/Android-Universal-Image-Loader#804]
EXAMPLE:

1) you have three image view objects: 

```
   imageView1 
   imageView2 
   imageView3
```

2) you have two image sources: http://server.com/a.jpg and http://server.com/b.jpg
3) than you need to download:

```
    http://server.com/a.jpg => imageView1
    http://server.com/a.jpg => imageView2
    http://server.com/b.jpg => imageView3
```

As a result of operations from above you will get:

```
    imageView1 (has image)
    imageView2 (no image - cancelled)
    imageView3 (has image)
```

How can I solve this issue?

P.S. Do I have any possibility to find that 

```
   a.jpg
```

in the memory or disc cache somehow?

**Comment by PicupMobile** [comment]
Hi Sergey,
Im using your 'com.nostra13.universalimageloader:universal-image-loader:1.9.5'
im getting two call here "ImageLoader.loadImage(...", and in my server i see two call for getImage api.
can you help please,

Thanks
Gil
