### ISSUE TITLE
Progress bar before image load

### ISSUE THREAD

**Issue by sagarmaiyad** [nostra13/Android-Universal-Image-Loader#854]
I want to show progress bar before image is load rather than display default image on imageview.

**Comment by mustafasevgi** [comment]
Thanks @nostra13.

**Comment by nagendraksrivastava** [comment]
@nostra13  can you guide me how to do the same thing , I want to display a small rounded progress while image is getting loaded , 
I am using below code but it is not working

mTalksDisplayImageOptions = new DisplayImageOptions.Builder()
                .cacheInMemory(true)
                .cacheOnDisk(true)
                .build();

mSpinner = new ProgressBar(context,null,android.R.attr.progressBarStyleSmall);

  mImageLoader.displayImage(talkImageThumbnil,talkImageView, mTalksDisplayImageOptions,new SimpleImageLoadingListener(){

                @Override
                public void onLoadingStarted(String imageUri, View view) {
                    mSpinner.setVisibility(View.VISIBLE);
                }

                @Override
                public void onLoadingFailed(String imageUri, View view, FailReason failReason) {
                    mSpinner.setVisibility(View.GONE);
                }

                @Override
                public void onLoadingComplete(String imageUri, View view, Bitmap loadedImage) {
                    mSpinner.setVisibility(View.GONE);
                }

                @Override
                public void onLoadingCancelled(String imageUri, View view) {
                    mSpinner.setVisibility(View.GONE);
                }

            });

**Comment by sbmaggarwal** [comment]
@nostra13 The link you provided for `ImageLoadingProgressListener ` seems to be broken. Can you just post the major part of the code here, if it possible? Or just update the link.

**Comment by nostra13** [comment]
Updated

**Comment by dinhduc0605** [comment]
@nostra13 why the ImageLoadingProgressListener not trigger. can you help me 

imageLoader.loadImage(LINK_FILE_ORIGIN + filename, null, options, new SimpleImageLoadingListener() {
                            @Override
                            public void onLoadingComplete(String imageUri, View view, Bitmap loadedImage) {
                                HelperFunction.saveBitmapStorage(loadedImage, filepath);
                                progressDialog.cancel();
                                Intent intent = new Intent(activity, FullSizeImageActivity.class);
                                intent.putExtra("filepath", filepath);
                                activity.startActivity(intent);
                            }
                        }, new ImageLoadingProgressListener() {
                            @Override
                            public void onProgressUpdate(String imageUri, View view, int current, int total) {
                                Log.w(TAG, "24234");
                            }
                        });
