### ISSUE TITLE
java.io.FileNotFoundException on android 2.3

### ISSUE THREAD

**Issue by HuangHanquan** [nostra13/Android-Universal-Image-Loader#870]
it does not open some urls on android 2.3 because of java.io.FileNotFoundException, for example http://img.sootuu.com/vector/2007-07-01/065/1/0406.gif. it is successful  that use HttpClient to load the image.

**Comment by nostra13** [comment]
Duplicated https://github.com/nostra13/Android-Universal-Image-Loader/issues/869
