### ISSUE TITLE
Download gif image file

### ISSUE THREAD

**Issue by lovehcf-duplicate** [nostra13/Android-Universal-Image-Loader#890]
I want to download a gif image file,but download the first frame.Can you help me?
My ImageLoaderConfiguration :
DisplayImageOptions defaultOptions = new DisplayImageOptions.Builder()
        .cacheInMemory(true)
        .cacheOnDisk(true)
        .bitmapConfig(Bitmap.Config.RGB_565)
        .imageScaleType(ImageScaleType.IN_SAMPLE_POWER_OF_2)
        .build();
		
		ImageLoaderConfiguration config = new ImageLoaderConfiguration.Builder(getApplicationContext())
		.threadPoolSize(5)
		.threadPriority(Thread.NORM_PRIORITY - 1)
		.memoryCache(new LruMemoryCache(1 * 1024 * 1024))
		.memoryCacheSize(1 * 1024 * 1024)//4MB
		.memoryCacheSizePercentage(13) 
		.denyCacheImageMultipleSizesInMemory()
		.tasksProcessingOrder(QueueProcessingType.FIFO)
		.defaultDisplayImageOptions(defaultOptions)
		.diskCache(new UnlimitedDiscCache(cacheDir)) // default
		.diskCacheFileNameGenerator(new HashCodeFileNameGenerator())
		.diskCacheExtraOptions(SCREEN_WIDTH, SCREEN_HEIGTH, defaultOptions.getPreProcessor())
		.build();
		ImageLoader.getInstance().init(config);

I download the gif image file code:
DisplayImageOptions mOptions = new DisplayImageOptions.Builder()
		.cacheInMemory(false)//don't memory cache
		.cacheOnDisk(true)
		.build();
		ImageLoader.getInstance().loadImage("http://img2.duitang.com/uploads/item/201303/15/20130315134323_PMTrz.gif",mOptions, new ImageLoadingListener() {
			@Override
			public void onLoadingStarted(String imageUri, View view) {				Logger.i(TAG, "download start imageUri-->" + imageUri);
			}
			
			@Override
			public void onLoadingFailed(String imageUri, View view,
					FailReason failReason) {
				Logger.i(TAG, "download failed");
			}
			
			@Override
			public void onLoadingComplete(String imageUri, View view, Bitmap loadedImage) {
				Logger.i(TAG, "download complete");
				File file = DiskCacheUtils.findInCache(imageUri,      ImageLoader.getInstance().getDiskCache());
				if(file != null && file.exists()){
					Logger.i(TAG, "file-->" + (file.length() / 1024.0f));
				}
			}
			
			@Override
			public void onLoadingCancelled(String imageUri, View view) {
				Logger.i(TAG, "download cancel");
			}
		});

**Comment by lovehcf-duplicate** [comment]
I know the reason,Thank you!

**Comment by brucetoo** [comment]
What reason ? can you tell me ?
