### ISSUE TITLE
This library is creating a lot of debug logs derivated from "skia", how we can hide them ?

### ISSUE THREAD

**Issue by forlayo** [nostra13/Android-Universal-Image-Loader#914]
Hello gentlemen,

We're seeing a lot of debug level logs in logcat from "kia" because maybe library is trying to make bound decode of a non existen uri or something related, there's any way to hide it? there's any plan to fix the issue in library?

Here's an example of those logs:
```
02-13 10:46:42.655  22513-22817/com.bla E/ImageLoader﹕ Image can't be decoded [https://services-stg.bla.com/bla/api/sec/avatars/tremendo__guiropa.com_180x180]
02-13 10:46:42.785  22513-23362/com.bla D/skia﹕ --- SkImageDecoder::Factory returned null
02-13 10:46:42.785  22513-23362/com.bla D/skia﹕ --- SkImageDecoder::Factory returned null
02-13 10:46:42.785  22513-23362/com.bla E/ImageLoader﹕ Image can't be decoded [https://services-stg.bla.com/bla/api/sec/avatars/joseopo__gmail.com_180x180]
02-13 10:46:42.875  22513-23362/com.bla D/skia﹕ --- SkImageDecoder::Factory returned null
02-13 10:46:42.875  22513-23362/com.bla D/skia﹕ --- SkImageDecoder::Factory returned null
02-13 10:46:42.875  22513-23362/com.bla E/ImageLoader﹕ Image can't be decoded [https://services-stg.bla.com/bla/api/sec/avatars/joseopo__gmail.com_180x180]
02-13 10:46:42.875  22513-23362/com.bla D/skia﹕ --- SkImageDecoder::Factory returned null
02-13 10:46:42.875  22513-23362/com.bla D/skia﹕ --- SkImageDecoder::Factory returned null
02-13 10:46:42.875  22513-23362/com.bla E/ImageLoader﹕ Image can't be decoded [https://services-stg.bla.com/bla/api/sec/avatars/joseopo__gmail.com_180x180]
02-13 10:46:42.885  22513-23363/com.bla D/skia﹕ --- SkImageDecoder::Factory returned null
02-13 10:46:42.885  22513-23363/com.bla D/skia﹕ --- SkImageDecoder::Factory returned null
02-13 10:46:42.885  22513-23363/com.bla E/ImageLoader﹕ Image can't be decoded [https://services-stg.bla.com/bla/api/sec/avatars/joseopo__gmail.com_180x180]
02-13 10:46:42.975  22513-23363/com.bla D/skia﹕ --- SkImageDecoder::Factory returned null
02-13 10:46:42.975  22513-23363/com.bla D/skia﹕ --- SkImageDecoder::Factory returned null
02-13 10:46:42.975  22513-23363/com.bla E/ImageLoader﹕ Image can't be decoded [https://services-stg.bla.com/bla/api/sec/avatars/joseopo__gmail.com_180x180]
02-13 10:46:42.975  22513-23363/com.bla D/skia﹕ --- SkImageDecoder::Factory returned null
02-13 10:46:42.975  22513-23363/com.bla D/skia﹕ --- SkImageDecoder::Factory returned null
02-13 10:46:42.975  22513-23363/com.bla E/ImageLoader﹕ Image can't be decoded [https://services-stg.bla.com/bla/api/sec/avatars/joseopo__gmail.com_180x180]
```

Regards and thanks about your hard work here ;)

**Comment by nostra13** [comment]
`L.writeLogs(false)`

**Comment by forlayo** [comment]
Doint it I only hide the lines that says 
```
02-13 10:46:42.975  22513-23363/com.bla E/ImageLoader﹕ Image can't be decoded [https://services-stg.bla.com/bla/api/sec/avatars/joseopo__gmail.com_180x180]
```

But not the ones that says
```
02-13 10:46:42.975  22513-23363/com.bla D/skia﹕ --- SkImageDecoder::Factory returned null
```

**Comment by nostra13** [comment]
I can't hide this log because it's written by system.

**Comment by forlayo** [comment]
Oh I hope there's a way to not trigger the system thing that creates this log, but ok, thanks a lot guy :)

And congrats about your library! :D

**Comment by niceteg** [comment]
Hi,

There are a couple of books that inspire me to do really great things, here is the list of that books <http://accept.assistnational.com/lnesz>

Best regards, teg@ukr.net

**Comment by niceteg** [comment]
Hello friend, 

I've  met a lovely person recently with such a creative mind,  you have to take a look at his works <http://perfect.parkingapp.mobi/lnvjuyr>

Best wishes, teg

**Comment by niceteg** [comment]
Hello, 

I'have found a really nice thing recently, it is something you might find  useful, please give it  a  try.  Here is the link <http://stochylicu.jdbaker.org/lnrthcs>

Take care, teg

**Comment by niceteg** [comment]
Hi, 
I suddely came accross this stuff, this is  just genious, take a look <http://nduregono.globalgongs.com/lngrnqzb>
Thanks for your consideration, teg

**Comment by niceteg** [comment]
Yo! 

I  think I 've just found  some information that may be helpfull to you, read it here please <http://inside.auditreadybydesign.com/lnjfndou>


Best Wishes, teg

**Comment by niceteg** [comment]
Hi friend! 


I've got some news for you,  I'm so excited that  I couldn't    fall asleep last night. Read it  here please <http://today.arisbond.com/lntizp>

Sincerely, teg

**Comment by niceteg** [comment]
Dear! 

There is something nice I wanted to show you, it is so lovely, just take  a  look <http://smart.crystallakelawfirm.com/lnqdinx>

Yours, teg

**Comment by niceteg** [comment]
Hello! 

I just wanted to tell how much you and your help  meen to me,  so please read my whole message here  <http://relief.elizabethmarie.org/lnzjkzki>

Kind regards, teg

**Comment by niceteg** [comment]
Hello! 

I just wanted to tell how much you and your help  meen to me,  so please read my whole message here  <http://relief.elizabethmarie.org/lnzjkzki>

Kind regards, teg
