### ISSUE TITLE
Multiple ImageLoader instances

### ISSUE THREAD

**Issue by artem-zinnatullin** [nostra13/Android-Universal-Image-Loader#92]
In my app I have got 3 types of images to load, all of types needed **different** ImageLoaderConfiguration. 
##### Images types example:
- Users avatars _(cache on disc, memory cache size ~ 5mb,  thread pool size ~ 3, thread priority min + 3, medium compression)_
- News feed pictures _(cache on disc, memory cache size ~ 1mb, thread pool size ~ 5, etc..)_
- Temporary images, like friends photos, etc.. _(no cache, thread pool size ~ 2,..)_

Sometimes it needed to use different ImageDownloader or FileNameGenerator or something else,  but it is not possible at the moment because ImageLoader is _singleton_ class.
#### So, what about many ImageLoader objects?

May be it will be good to use ImageLoaderFactory and class-containter for created ImageLoader objects to use them, or something else.

What do you think about it?

**Comment by hubcin** [comment]
Thank you for the great library ! I'm using it now and it's working perfect. I've been reading you code for days to find out how to cache images in different folders, for example, I wanna cache user profile image in /profile folder and others in /other folder, and I wanna be able to clean the /profile folder separately . How should I implement this ? Thanks.
