### ISSUE TITLE
Can i use a gif for ImageOnLoading?

### ISSUE THREAD

**Issue by rmuhamed** [nostra13/Android-Universal-Image-Loader#924]
I need to put a kind of ProgressBar or animated drawable during the Image loading, is this possible?

UIL version: 1.9.3 with sources

Environment: Eclipse 4.2

Deploy Android version >= 2.3.3

My Configuration

		DisplayImageOptions.Builder builder = new DisplayImageOptions.Builder();
		builder.bitmapConfig(Config.RGB_565);
		builder.imageScaleType(ImageScaleType.IN_SAMPLE_INT);
		builder.cacheInMemory(true);
		
		builder.showImageOnLoading(c.getResources().getDrawable(R.drawable.image_download_placeholder));
		builder.showImageOnFail(c.getResources().getDrawable(R.drawable.image_download_fail));
		
		DisplayImageOptions options = builder.build();
		// Create global configuration and initialize ImageLoader with this config
		ImageLoaderConfiguration.Builder imageLoaderBuilder = new ImageLoaderConfiguration.Builder(c);
		imageLoaderBuilder.threadPoolSize(5);
		imageLoaderBuilder.memoryCacheSize(2 * 1024 * 1024);
		imageLoaderBuilder.diskCacheExtraOptions(240, 320, null);
		imageLoaderBuilder.defaultDisplayImageOptions(options);
		
		ImageLoader.getInstance().init(imageLoaderBuilder.build());

Thanks in advance!

**Comment by zdd** [comment]
Look into the sample code, it has the progress bar on loading.

**Comment by rmuhamed** [comment]
Ouch, Sorry! i don't try this variant.

Thaks!
