### ISSUE TITLE
Disk Cache

### ISSUE THREAD

**Issue by jjcardonao** [nostra13/Android-Universal-Image-Loader#941]
How do I change the URL where the images are saved (disk cache)?

**Comment by chrisjluc** [comment]
```
File cacheDir = StorageUtils.getIndividualCacheDirectory(context, "AppDir/cache/images");

ImageLoaderConfiguration config = new ImageLoaderConfiguration.Builder(context)
        .diskCache(new UnlimitedDiscCache(cacheDir))
        ...
        .build();
```

You can use either `getIndividualCacheDirectory` or `getOwnCacheDirectory`, it depends on your use case.

Look at the [source code](https://github.com/nostra13/Android-Universal-Image-Loader/blob/master/library/src/com/nostra13/universalimageloader/utils/StorageUtils.java#L109) for more info.

**Comment by jjcardonao** [comment]
don't work yet :P with version 1.9.3
